name: Release
on:
  workflow_dispatch:
env:
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'legacy-v3'

      - uses: actions/setup-node@v3
        with:
          node-version: node

      - run: |
          npm ci
          npm i @spgoding/datapack-language-server@latest --save-exact
          npm version patch --git-tag-version=false
          npm run build
          git add .
          git commit -m "released"

      - run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      
      - run: |
          ./script/removeExtensionDependencies.mjs
          npx ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

      - run: git push
